# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('tag_line', models.CharField(max_length=140)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='output',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Project'),
        ),
        migrations.AddField(
            model_name='input',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Project'),
        ),
    ]
